fieldLayouts:
  e1c89fce-1e23-40de-af30-2a5bcc65a0cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0828b61a-0250-4639-9f7b-e6405df5096e
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 07d75007-ee62-4297-b06a-cabb875b8ccc
        userCondition: null
handle: tags
name: Tags
