fieldLayouts:
  2248acc0-6c6e-4e03-bcf4-25f55297bd18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:07:34-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b # WordPress ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1faded8a-6123-4194-a7f9-47aa5818ffe4
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 55c7a505-2b6f-464f-b30b-3c765be8a4e5
        userCondition: null
handle: tags
name: Tags
