color: cyan
fieldLayouts:
  8e66f200-771e-400d-ac5e-f3564767ebaa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T17:17:11-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d8cd19e7-4360-4ce5-a8af-c3ac31d6e476
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:17:11-08:00'
            elementCondition: null
            fieldUid: 22e94a09-0f7c-4a1f-9981-7fc0605d83fa # Link URL
            handle: buttonUrl
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2946bfc0-d55e-4140-9ee7-a6b25bebff24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d11d7621-445f-4657-a552-da3f78ac077a
        userCondition: null
handle: button
hasTitleField: true
icon: link
name: Button
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
