color: blue
fieldLayouts:
  27b3c5f6-41ad-4c1a-967f-b8fe019546b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-07T04:34:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: afa791df-110e-4906-85f2-d0f1b3cd07b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T04:37:04+00:00'
            elementCondition: null
            fieldUid: 68d4b67e-54f4-47c9-97cb-ff232d3d1e24 # Image
            handle: logo
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55e7e0d1-35c1-43a0-b318-9f719786aaab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T04:37:04+00:00'
            elementCondition: null
            fieldUid: 3944dd4b-41c9-40e5-abee-b4a365a25540 # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 829e0dec-f216-4835-af4f-9fb2854ff8d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 251f853b-ef8a-4c7a-acdb-922ca32d6903
        userCondition: null
handle: global
hasTitleField: true
icon: globe
name: Global
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
