color: blue
fieldLayouts:
  20bcbbe0-6a96-443c-9b65-bca58d18b488:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T17:34:24-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9622156f-41a9-4f11-8558-f5447e0d51ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: e314b2cd-4ad3-4d8c-94d8-347ddb16245d # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1489223-df13-4524-9282-4dabab5d5029
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c308d441-0b80-4221-b091-39e04c9d27ce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9
            handle: coverText
            includeInCards: false
            instructions: null
            label: 'Cover Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 256f311d-a99d-4421-8033-8463d0107eb6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: coverPhoto
            includeInCards: false
            instructions: null
            label: 'Cover Photo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5dc91c8-cf7b-4a36-9f5d-88aa5f566238
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: ec2af108-def7-419e-b9fd-53f0d4289b0d # Color
            handle: coverOverlayColor
            includeInCards: false
            instructions: null
            label: 'Cover Overlay Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24f26ae7-e667-4763-b42e-f47a025a7ef5
            userCondition: null
            warning: null
            width: 100
        name: 'Cover Photo'
        uid: 0d04fc4d-e749-4fc6-8755-154c62bd849d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: 25ac5e32-778c-48a8-8600-4e9e1a092216 # Publication
            handle: publication
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2ac0f94-a361-4896-996f-982d0905c29f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: 39a52cc1-2152-4f07-8a95-2768570e084d # Date
            handle: date
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4af9204-94fb-4a2e-a74e-8462ed3e8ad6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: dc4d106e-d508-4308-869a-7e2b8434efbe # URL
            handle: url_acf
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b913a90-f125-4061-a4d8-a65134fc5e86
            userCondition: null
            warning: null
            width: 100
        name: 'For Interviews'
        uid: c6dab5d2-aef2-4b73-b10c-3927a9c09592
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: 79559275-ab81-4420-abf1-1c848a0a68d6 # Sticky
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03feac81-4322-4e53-8414-80da776903aa
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 454fb125-65c0-4fec-b48a-84ae65b6dd7b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 192a2c2b-4014-4083-8276-1824022965df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:24-08:00'
            elementCondition: null
            fieldUid: 7e2aabf9-48f2-4671-b232-546499a18d43 # Template
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b531c5be-3b7f-4280-bdb7-6d033490f487
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 9bcd53f6-fa8d-4bd7-bdef-2cceae35cc1e
        userCondition: null
handle: interview
hasTitleField: true
icon: pen-nib
name: Interview
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
