color: amber
fieldLayouts:
  457e872c-7591-4467-97fd-92ab0a11ac96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:09:03-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b94fd69-57f6-4780-93ac-325225ac867b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 381a3cfa-4dcb-46b7-8fcf-73295b37a55f
        userCondition: null
handle: media
hasTitleField: false
icon: photo-film-music
name: Media
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
