color: blue
fieldLayouts:
  9e85be60-e649-4df4-a767-2e145fe14956:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T17:34:18-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 507fb86e-ffbb-4a19-a063-19e811fc9258
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: e314b2cd-4ad3-4d8c-94d8-347ddb16245d # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 525754a0-6f51-4f3a-b627-a56d82fbc985
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2e6f3674-48ab-46ec-829e-3d5de63d838c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9
            handle: coverText
            includeInCards: false
            instructions: null
            label: 'Cover Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70584295-1b8d-415f-b4b7-c7c67a795fc9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: coverPhoto
            includeInCards: false
            instructions: null
            label: 'Cover Photo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fff0144c-abf7-4fcb-9a70-f009ef12a684
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: ec2af108-def7-419e-b9fd-53f0d4289b0d # Color
            handle: coverOverlayColor
            includeInCards: false
            instructions: null
            label: 'Cover Overlay Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: decf8fbf-d45f-4b63-99c5-bb3565968d12
            userCondition: null
            warning: null
            width: 100
        name: 'Cover Photo'
        uid: 8871d519-01ec-483f-9421-f01d45d2c34f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1b1fb32-9bbb-4aad-b2e0-f8c4ae8e53a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: c23bcc94-9f9b-42ae-aca6-b5afb8be5e86 # Comment Options
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98d126e5-fbc8-4650-97df-48d733b64287
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: f3e86d31-d063-42a5-8bf3-130f018f7933
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64446613-dd10-4f7c-aadc-a4c825c27cdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:34:18-08:00'
            elementCondition: null
            fieldUid: 7e2aabf9-48f2-4671-b232-546499a18d43 # Template
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2b785dc-da05-43e5-a218-17acad33b28f
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: f82f1443-6859-4cfc-94f7-d23ebf24dbc4
        userCondition: null
handle: page
hasTitleField: true
icon: page
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
