color: blue
fieldLayouts:
  a33ef0a7-64ba-4e9f-9f60-0e217e2b517e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T07:14:41-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 80c6c343-0cc2-40bc-8b44-5746df5b7c8e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: e314b2cd-4ad3-4d8c-94d8-347ddb16245d # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef1bb168-3992-42e8-8c3e-7c8adefa6f8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: edeb6d71-e44a-40bf-96bd-b6bd3c8d67fe
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9 # Description
            handle: coverText
            includeInCards: false
            instructions: null
            label: 'Cover Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eca028e-b7aa-437f-9745-3538305a26d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: coverPhoto
            includeInCards: false
            instructions: null
            label: 'Cover Photo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4789986-de84-46f2-828f-5e61f478a751
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: ec2af108-def7-419e-b9fd-53f0d4289b0d # Color
            handle: coverOverlayColor
            includeInCards: false
            instructions: null
            label: 'Cover Overlay Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07e3b92d-74ec-4d93-89cb-b8bf8e610a8c
            userCondition: null
            warning: null
            width: 100
        name: 'Cover Photo'
        uid: 3a37cd30-71ee-47e1-9972-2fd5d5344cac
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f620f54a-be68-40ac-a5b2-e6c5afe51b1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: c23bcc94-9f9b-42ae-aca6-b5afb8be5e86 # Comment Options
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8759f46d-9b36-4567-99ee-2a57a01b59ad
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 7ed33e95-b855-4778-bd0c-be249c8b4ca0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b # WordPress ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67067493-598f-47db-98e2-ac88a126591c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:41-08:00'
            elementCondition: null
            fieldUid: 7e2aabf9-48f2-4671-b232-546499a18d43 # Template
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fea6b82-0523-47cf-a9cd-389f774f1f90
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 0486decc-315f-4da4-ae68-f13d3c350b03
        userCondition: null
handle: page
hasTitleField: true
icon: page
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
