color: blue
fieldLayouts:
  09a2f59d-d2b8-4f6d-b93a-793f7d859069:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T17:09:01-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5acf59d4-5546-4053-a487-cca992a139ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: e314b2cd-4ad3-4d8c-94d8-347ddb16245d # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c5542f0-d669-43b2-959c-5cf90946837d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 189d5714-d1fa-4167-8d2c-0b021e0b8a8b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9
            handle: coverText
            includeInCards: false
            instructions: null
            label: 'Cover Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e6ae204-e5ff-46d3-a092-4b09057cbe43
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: coverPhoto
            includeInCards: false
            instructions: null
            label: 'Cover Photo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b199fd0-e30a-4fe1-88bd-a3138772a172
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: ec2af108-def7-419e-b9fd-53f0d4289b0d # Color
            handle: coverOverlayColor
            includeInCards: false
            instructions: null
            label: 'Cover Overlay Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bbd51a0-b9dd-4038-9b3b-eed933b7ef87
            userCondition: null
            warning: null
            width: 100
        name: 'Cover Photo'
        uid: 5a3f7d76-bc72-4508-9708-d8068cfe8d43
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b013c70e-928f-40e9-acab-146e56fb8e0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: 4c8edf71-ef0c-4ba3-ba4e-cf0ef5ac36ea
            handle: excerpt
            includeInCards: false
            instructions: null
            label: Excerpt
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81d84772-6888-48ca-a399-028ed61c203d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: c23bcc94-9f9b-42ae-aca6-b5afb8be5e86 # Comment Options
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d4cf859-c9db-458e-a032-45a0226f84d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: d958a069-fc64-431a-91bc-3141612304be # Format
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf47f04b-d48b-462d-98de-2a78608d33d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: 79559275-ab81-4420-abf1-1c848a0a68d6 # Sticky
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b936b8ea-342d-4443-9fc7-73ba998a362b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: b10bb931-be55-44fc-ade2-a3d5603ac315 # Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9a80edb-26cb-4967-8cea-69a6310fbbbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: b6c4299e-6af3-4049-9566-14675dad34d7 # Genres
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be8dfe09-c484-4c63-a8db-309330b0226b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: 5a524179-b073-4ec2-a219-674143dbc455 # Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 383ec33b-0b8f-4d54-b8a7-72b15c982af5
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: de3e3cc0-0fad-496f-b5c9-4cb85fe1e08d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ebde98e-181c-4be5-b528-1d45f5983620
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:01-08:00'
            elementCondition: null
            fieldUid: 7e2aabf9-48f2-4671-b232-546499a18d43 # Template
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 519fb427-9233-4a8b-ad48-820bb441499a
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: ca871573-0b38-41c1-82d7-1fe036060a5e
        userCondition: null
handle: post
hasTitleField: true
icon: thumbtack
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
