color: blue
fieldLayouts:
  175a8bd3-9a2b-4051-92a3-2f608e87f73e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T07:14:36-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5dcaf32c-8d32-41b8-963e-a6339e7c3eca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: e314b2cd-4ad3-4d8c-94d8-347ddb16245d # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1da29e5-1c6a-4b6e-8065-4b389558e2b1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23d7ad6b-ae8a-47a2-9e29-e8d40b412b66
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9 # Description
            handle: coverText
            includeInCards: false
            instructions: null
            label: 'Cover Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 530f9996-4a9e-4b82-9306-8163f849e4f8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: coverPhoto
            includeInCards: false
            instructions: null
            label: 'Cover Photo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47551087-4d6c-467a-980e-3ab0183e4ad5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: ec2af108-def7-419e-b9fd-53f0d4289b0d # Color
            handle: coverOverlayColor
            includeInCards: false
            instructions: null
            label: 'Cover Overlay Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a97093d-0ffe-4470-83ae-411a490a154e
            userCondition: null
            warning: null
            width: 100
        name: 'Cover Photo'
        uid: 210b0f26-7900-4d54-ab14-d6dd7c238f54
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: a553e2eb-f7c3-4f3e-a07e-27f4c94cec86 # Media
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0f2c1e6-d20d-4881-8a64-ee0303c72649
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: 4c8edf71-ef0c-4ba3-ba4e-cf0ef5ac36ea # Caption
            handle: excerpt
            includeInCards: false
            instructions: null
            label: Excerpt
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0623cd57-5fa9-4e93-8621-f6035d95ab1b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: c23bcc94-9f9b-42ae-aca6-b5afb8be5e86 # Comment Options
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91113108-d81c-4618-bb48-7605dc608bee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: d958a069-fc64-431a-91bc-3141612304be # Format
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41644723-bd54-4b89-8c3d-967eeb14503b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: 79559275-ab81-4420-abf1-1c848a0a68d6 # Sticky
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4117f6bc-1568-4335-ad9b-beae1e9bd445
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: 4ed3764f-e784-4258-8dd8-b9b0217225ab # Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 452aee03-f605-4617-9d2c-5227b04f6862
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: 5a524179-b073-4ec2-a219-674143dbc455 # Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8af27417-a13c-449e-b095-5b662482c98d
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: bc612942-9b02-46b8-a218-9009b6405140
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b # WordPress ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7c1fb75-f575-48c8-aa7f-83af9ce0febe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:14:36-08:00'
            elementCondition: null
            fieldUid: 7e2aabf9-48f2-4671-b232-546499a18d43 # Template
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cbc0449-ec17-410e-9078-c052adb42d98
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 97798985-8eac-4e3f-b5bc-00dff93c9ad9
        userCondition: null
handle: post
hasTitleField: true
icon: thumbtack
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
