headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Post Content'
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - '|'
  - blockQuote
  - bulletedList
  - numberedList
  - codeBlock
  - '|'
  - insertTable
  - mediaEmbed
  - htmlEmbed
  - horizontalLine
  - pageBreak
  - '|'
  - createEntry
  - sourceEditing
