headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
toolbar:
  - heading
  - bold
  - italic
  - bulletedList
  - numberedList
  - blockQuote
  - alignment
  - link
  - pageBreak
  - '|'
  - strikethrough
  - horizontalLine
  - fontColor
  - removeFormat
  - outdent
  - indent
  - undo
  - redo
