defaultPlacement: end
fieldLayouts:
  e545069c-ad53-4d32-9d8d-4cdef29b9748:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T07:07:36-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: d70d9b23-a456-4887-ab8b-e4e02e6cdc9c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:07:36-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7493c3e-27bb-4c21-8eb9-06e4b62d4e37
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d534632-4d97-4790-9b5d-f02a482efa4e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:07:36-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b # WordPress ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c62f46c-d495-4d57-866a-91cf505cfc3f
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 846a16aa-1be0-4830-980c-506dda479ced
        userCondition: null
handle: categories
name: Categories
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # WordPress Starter
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 76082846-0dec-45ba-bb35-443883117214
