defaultPlacement: end
fieldLayouts:
  21e1691d-fd34-48ca-bb40-715ae2f1b967:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-07T01:09:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 0bc95522-8139-48bf-86c7-b1a6cce0dce8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T01:09:01+00:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 649c8f52-36df-4278-a371-09ad1b27b8e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1d78146-ad20-42f2-ba8c-93191110cca8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T01:09:01+00:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e91e9133-210f-4cf7-9af5-4b437fee9f8c
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: 0a0e6275-610c-4deb-8403-7d83d7f60970
        userCondition: null
handle: categories
name: Categories
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # Wordpress Starter
    hasUrls: true
    template: pages/category.twig
    uriFormat: 'category/{slug}'
structure:
  maxLevels: null
  uid: 04824fff-3cab-4760-9023-a9700dafba0b
