tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-11-07T01:09:01+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\UsernameField
        uid: 2089871e-73e1-4a43-a20e-b641d4b5d25b
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-11-07T01:09:01+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: 3395598a-37e4-456b-b9d0-d970914b05d1
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-11-07T01:09:01+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: 184ef975-f667-4fd1-a9c9-c322a83d1534
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-11-07T01:09:01+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: ed7157b2-3e81-43f7-a8ed-7630c10ae5a8
        userCondition: null
        width: 100
    name: Content
    uid: a3aba2ec-58b5-4072-8579-1d7b4cf9308b
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        dateAdded: '2024-11-13T07:14:36-08:00'
        elementCondition: null
        fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b # WordPress ID
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b49b7043-67de-4df9-839a-4bcbce02c5a5
        userCondition: null
        warning: null
        width: 100
    name: WordPress
    uid: 5ac74434-e3bc-440d-8254-0fbf2641663f
    userCondition: null
