altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f7fe71e2-b0eb-455b-a1d3-fc18574edaa1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-13T07:07:28-08:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 11a3c082-3f34-4058-89b2-b0ff9e09c355
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:07:28-08:00'
            elementCondition: null
            fieldUid: 4c8edf71-ef0c-4ba3-ba4e-cf0ef5ac36ea # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a354d5d-c14a-4fee-97f8-ca2d2bddd0ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T07:07:28-08:00'
            elementCondition: null
            fieldUid: b636e420-0741-4bd3-b8b2-89a8d50806f9 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc533093-388d-4bf4-a703-94915293bd7b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ee70d7e-841f-45fe-b990-a29b2636b086
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T07:07:28-08:00'
            elementCondition: null
            fieldUid: 4d06012a-2d8a-4e92-bf6b-de74bdd1be0b # WordPress ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c89a5474-593a-4564-b594-d25fa745095d
            userCondition: null
            warning: null
            width: 100
        name: WordPress
        uid: d87e28a2-21f7-4207-9e77-03d1a737d3fe
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
