columnSuffix: null
handle: acf_postObject_11677
instructions: ''
name: 'Post Object'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:d147c081-e3fc-42d9-9991-1e915a0d70e2' # Pages
    - 'section:d69a256f-5a90-4a31-8d8e-f5cac78994f9' # Interviews
    - 'section:0860788f-c61f-488d-b0e6-3de270710945' # Posts
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
