columnSuffix: null
handle: acf_timelineType_5865
instructions: ''
name: 'Timeline Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Life Label'
        -
          - value
          - Life
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - 'School Label'
        -
          - value
          - School
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - 'Work Label'
        -
          - value
          - Work
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - 'Project Label'
        -
          - value
          - Project
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
