columnSuffix: null
handle: acf_checkboxes_11650
instructions: ''
name: Checkboxes
searchable: false
settings:
  customOptions: true
  options:
    -
      __assoc__:
        -
          - label
          - Red
        -
          - value
          - red
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - Green
        -
          - value
          - green
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - blue
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
