columnSuffix: null
handle: acf_link_11654
instructions: ''
name: Link
searchable: false
settings:
  maxLength: 255
  showLabelField: true
  showTargetField: true
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
