columnSuffix: null
handle: acf_genreLink_11671
instructions: ''
name: 'Genre Link'
searchable: false
settings:
  maxLength: 255
  showLabelField: true
  showTargetField: true
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
