columnSuffix: null
handle: acf_range_11642
instructions: ''
name: Range
searchable: false
settings:
  defaultValue: null
  max: 100
  min: 0
  numberInputSize: 5
  step: 10
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
