columnSuffix: null
handle: acf_swich_11653
instructions: ''
name: Swich
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
