columnSuffix: null
handle: color
instructions: null
name: Color
searchable: false
settings:
  defaultColor: null
  presets:
    - '#000000'
    - '#abb8c3'
    - '#ffffff'
    - '#f78da7'
    - '#cf2e2e'
    - '#ff6900'
    - '#fcb900'
    - '#7bdcb5'
    - '#00d084'
    - '#8ed1fc'
    - '#0693e3'
    - '#9b51e0'
    - '#f9f9f9'
    - '#111111'
    - '#636363'
    - '#a4a4a4'
    - '#cfcabe'
    - '#c2a990'
    - '#d8613c'
    - '#b1c5a4'
    - '#b5bdbc'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
