columnSuffix: null
handle: commentOptions
instructions: null
name: 'Comment Options'
searchable: false
settings:
  commentEnabled: true
  default: true
translationKeyFormat: null
translationMethod: none
type: verbb\comments\fields\CommentsField
