columnSuffix: null
handle: format
instructions: null
name: Format
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Standard
        -
          - value
          - standard
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - Aside
        -
          - value
          - aside
    -
      __assoc__:
        -
          - label
          - Audio
        -
          - value
          - audio
    -
      __assoc__:
        -
          - label
          - Chat
        -
          - value
          - chat
    -
      __assoc__:
        -
          - label
          - Gallery
        -
          - value
          - gallery
    -
      __assoc__:
        -
          - label
          - Image
        -
          - value
          - image
    -
      __assoc__:
        -
          - label
          - Link
        -
          - value
          - link
    -
      __assoc__:
        -
          - label
          - Quote
        -
          - value
          - quote
    -
      __assoc__:
        -
          - label
          - Status
        -
          - value
          - status
    -
      __assoc__:
        -
          - label
          - Video
        -
          - value
          - video
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
