columnSuffix: null
handle: postContent
instructions: null
name: 'Post Content'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 7261a233-a194-4374-8a55-91770cef7528 # Post Content
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  entryTypes:
    - d2356f61-430b-423e-a52e-a167fc52ba47 # Media
    - 36ca6464-18ad-4f2a-9ae0-e8da4e00c94a # Group
    - fc8630bf-cc94-4830-8e52-40246afab5e5 # Button
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
