columnSuffix: null
handle: wpId
instructions: null
name: 'WordPres ID'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
