dateModified: 1730949519
email:
  fromEmail: travis@pixelandtonic.com
  fromName: 'Wordpress Starter'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    b66f8abd-d112-4e22-9970-c8ecc1641395: 'Wordpress Starter' # Wordpress Starter
    ef8dfbdb-4e28-4c5b-be56-2d0c840c772d: 'Wordpress Starter' # Wordpress Starter
system:
  edition: solo
  live: true
  name: 'Wordpress Starter'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
