dateModified: 1731513080
email:
  fromEmail: travis@pixelandtonic.com
  fromName: travis@pixelandtonic.com
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: /uploads
meta:
  __names__:
    0ff5ed7e-a51c-4d65-82bc-8a9b37bea3c8: WordPress # WordPress
    4c8edf71-ef0c-4ba3-ba4e-cf0ef5ac36ea: Caption # Caption
    4d06012a-2d8a-4e92-bf6b-de74bdd1be0b: 'WordPress ID' # WordPress ID
    4ed3764f-e784-4258-8dd8-b9b0217225ab: Categories # Categories
    5a524179-b073-4ec2-a219-674143dbc455: Tags # Tags
    5f525fa3-84a6-4713-9965-876e50137a67: Page # Page
    7e2aabf9-48f2-4671-b232-546499a18d43: Template # Template
    08a529f2-1255-4bc6-9680-ec89d97b23fa: 'Public Schema' # Public Schema
    8e453d04-2511-44eb-b3dc-0d53fa2ab198: Posts # Posts
    22e94a09-0f7c-4a1f-9981-7fc0605d83fa: 'Link URL' # Link URL
    36ca6464-18ad-4f2a-9ae0-e8da4e00c94a: Group # Group
    599eac19-621a-42b0-bf98-006466ac4618: Post # Post
    677c2b2b-14a7-4692-8bb8-b4dc667e1a12: Tags # Tags
    7261a233-a194-4374-8a55-91770cef7528: 'Post Content' # Post Content
    37938585-7d7b-4d97-94f7-73dc07d795c2: 'WordPress Starter' # WordPress Starter
    79559275-ab81-4420-abf1-1c848a0a68d6: Sticky # Sticky
    a553e2eb-f7c3-4f3e-a07e-27f4c94cec86: Media # Media
    b636e420-0741-4bd3-b8b2-89a8d50806f9: Description # Description
    ba83893c-c85d-4d01-81a2-0dfc8723fb5d: Uploads # Uploads
    c23bcc94-9f9b-42ae-aca6-b5afb8be5e86: 'Comment Options' # Comment Options
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    cde05efd-18e0-4859-9690-3559eb5155b2: Pages # Pages
    d958a069-fc64-431a-91bc-3141612304be: Format # Format
    d2356f61-430b-423e-a52e-a167fc52ba47: Media # Media
    e314b2cd-4ad3-4d8c-94d8-347ddb16245d: 'Post Content' # Post Content
    ec2af108-def7-419e-b9fd-53f0d4289b0d: Color # Color
    f5e7728b-1e73-479d-a629-15f7e1276a3c: Categories # Categories
    fc8630bf-cc94-4830-8e52-40246afab5e5: Button # Button
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  comments:
    edition: standard
    enabled: true
    licenseKey: GTB6N9BJ9LJ9MWDKLCZUPN45
    schemaVersion: 1.2.0
    settings:
      allowFlagging: true
      allowGuest: false
      allowGuestFlagging: false
      allowGuestVoting: false
      allowVoting: true
      autoCloseDays: null
      closed: false
      defaultQueryStatus:
        - approved
      downvoteCommentLimit: 5
      enableGravatar: false
      enableSpamChecks: true
      flaggedCommentLimit: 5
      guestNotice: null
      guestRequireEmailName: true
      guestShowEmailName: true
      hideVotingForThreshold: false
      indexSidebarGroup: true
      indexSidebarIndividualElements: false
      indexSidebarLimit: 25
      maxReplyDepth: null
      maxUserComments: null
      moderatorExcluded: true
      moderatorUserGroup: null
      notificationAdminEnabled: false
      notificationAuthorEnabled: true
      notificationFlaggedEnabled: false
      notificationModeratorApprovedEnabled: false
      notificationModeratorEditEnabled: false
      notificationModeratorEnabled: false
      notificationReplyEnabled: true
      notificationSubscribeAuto: false
      notificationSubscribeCommentEnabled: false
      notificationSubscribeDefault: true
      notificationSubscribeEnabled: false
      orderBy: desc
      outputDefaultCss: true
      outputDefaultJs: true
      permissions:
        __assoc__:
          -
            - craft\elements\Asset
            - '*'
          -
            - craft\elements\Category
            - '*'
          -
            - craft\elements\Entry
            - '*'
          -
            - craft\elements\User
            - '*'
      placeholderAvatar: null
      pluginName: Comments
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      requireModeration: true
      securityBanned: null
      securityFlooding: null
      securityMatchExact: false
      securityMaxLength: null
      securityModeration: null
      securitySpamlist: null
      showAvatar: true
      showCustomFieldInstructions: false
      showCustomFieldNames: false
      showTimeAgo: true
      sortDefaultDirection: asc
      sortDefaultKey: structure
      structureUid: 8487d65a-a2c4-4395-bebd-987bc761fa11
      templateEmail: null
      templateFolderOverride: null
      useQueueForNotifications: false
system:
  edition: team
  live: true
  name: 'WordPress Starter'
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
