defaultPlacement: end
enableVersioning: false
entryTypes:
  - 95960eea-4a79-4e72-960f-516e4e24f7a4
handle: actionItems
maxAuthors: 1
name: 'Action Items'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # Wordpress Starter
    enabledByDefault: true
    hasUrls: true
    template: _post.twig
    uriFormat: '{postDate|date(''Y'')}/{postDate|date(''m'')}/{slug}'
type: channel
