defaultPlacement: end
enableVersioning: false
entryTypes:
  - 7376411d-2303-4b5f-b4f3-3e6be9b8ae30
handle: conferences
maxAuthors: 1
name: Conferences
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # Wordpress Starter
    enabledByDefault: true
    hasUrls: true
    template: _post.twig
    uriFormat: '{postDate|date(''Y'')}/{postDate|date(''m'')}/{slug}'
type: channel
