defaultPlacement: end
enableVersioning: true
entryTypes:
  - 23a3f2f7-2b22-4a38-835a-342440a6a2ce # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # Wordpress Starter
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
