defaultPlacement: end
enableVersioning: false
entryTypes:
  - 7e840cd6-eb2d-44b1-a20a-ca7ba60b1fc2 # Interview
handle: interviews
maxAuthors: 1
name: Interviews
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # Wordpress Starter
    enabledByDefault: true
    hasUrls: true
    template: _post.twig
    uriFormat: '{postDate|date(''Y'')}/{postDate|date(''m'')}/{slug}'
type: channel
