defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5f525fa3-84a6-4713-9965-876e50137a67 # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # WordPress Starter
    enabledByDefault: true
    hasUrls: true
    template: _post.twig
    uriFormat: '{postDate|date(''Y'')}/{postDate|date(''m'')}/{postDate|date(''d'')}/{slug}'
structure:
  maxLevels: null
  uid: 380c18db-0864-44f8-87e6-799d2f2656bc
type: structure
