defaultPlacement: end
enableVersioning: true
entryTypes:
  - 599eac19-621a-42b0-bf98-006466ac4618 # Post
handle: posts
maxAuthors: 1
name: Posts
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  37938585-7d7b-4d97-94f7-73dc07d795c2: # WordPress Starter
    enabledByDefault: true
    hasUrls: true
    template: _post.twig
    uriFormat: '{postDate|date(''Y'')}/{postDate|date(''m'')}/{postDate|date(''d'')}/{slug}'
type: channel
